name: smap_io-docs
channels:
- conda-forge
dependencies:
- h5py
- python=3.6
- pyresample
- scipy
- pandas
- netcdf4
- matplotlib
- sphinx
- pip:
  - pygeobase
  - pytesmo
  - pygeogrids
  - repurpose
  - ease_grid
